Asset/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.schemas import get_schema_view
from cmdb.views import account, home
from cmdb.views import asset
from cmdb.views import user
from cmdb.views import api
from cmdb.views.api import ReturnJson
from cmdb import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/',views.index),
    url(r'^^$',views.homepage),
    url(r'^api_post/',api.post_asset.as_view()),
    url(r'^account/', account.LoginView.as_view()),
    url(r'^asset/', asset.AssetInfo.as_view(),name="asset"),
    url(r'^location/', asset.Location.as_view(),name="location"),
    url(r'^dcroom/', asset.Location.as_view(),name="location"),
    url(r'^home/', home.Index.as_view()),
    url(r'^user/', user.Userinfo.as_view()),
    url(r'^detail/',asset.AssetDetail.as_view()),
    url(r'^audit_asset/', api.AuditAsset.as_view(),name="add_assets"),
    url(r'^docs/', get_schema_view()),
    url(r'^api/get_idc', ReturnJson.as_view()),
    url(r'^api/get_asset', ReturnJson.as_view()),
    # url(r'^layout.html', api.layoutview.as_view()),
    url(r'^header_menu.html', api.header.as_view()),
    url(r'^search/', views.search.as_view()),
    url(r'^popover/', views.popover),

]

api/urls.py
#/usr/bin/env python
#-*- coding: utf-8 -*-
from django.conf.urls import url
from .views import *
# urlparterns = [
urlpatterns = [
    url(r'^post_asset/', post_asset.as_view()),
]

cmdb/models.py
from django.db import models

class Per(models.Model):
    name = models.CharField("权限名称", max_length=64)
    url = models.CharField('URL名称', max_length=255)
    chioces = ((1, 'GET'), (2, 'POST'))
    PerMethod = models.SmallIntegerField('请求方法', choices=chioces, default=1)
    argument_list = models.CharField('参数列表', max_length=255, help_text='多个参数之间用英文半角逗号隔开', blank=True, null=True)
    describe = models.CharField('描述', max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '权限表'
        verbose_name_plural = verbose_name
        # 权限信息，这里定义的权限的名字，后面是描述信息，描述信息是在django admin中显示权限用的
        permissions = (
            ('add_location', '添加数据中心'),
            ('edit_location', '编辑数据中心'),
            ('audit_assets', '资产审核权限'),
            ('add_assets', '添加资产信息'),
            ('edit_assets', '已录资产编辑'),
            ('del_assets', '已录资产删除'),
        )
class UserGroup(models.Model):
    """
    用户组
    """
    name = models.CharField(max_length=32, unique=True)
    users = models.ManyToManyField('UserProfile')
    class Meta:
        verbose_name_plural = "用户组表"
    def __str__(self):
        return self.name
class UserProfile(models.Model):
    """
    用户信息
    """
    name = models.CharField(u'姓名', max_length=32)
    email = models.EmailField(u'邮箱')
    phone = models.CharField(u'座机', max_length=32)
    mobile = models.CharField(u'手机', max_length=32)
    class Meta:
        verbose_name_plural = "用户表"
    def __str__(self):
        return self.name
class BusinessUnit(models.Model):
    """
    业务线
    """
    name = models.CharField('业务线', max_length=64, unique=True)
    contact = models.ForeignKey('UserGroup', verbose_name='业务联系人', related_name='c',on_delete=models.CASCADE) # 多个人
    manager = models.ForeignKey('UserGroup', verbose_name='系统管理员', related_name='m',on_delete=models.CASCADE) # 多个人
    class Meta:
        verbose_name_plural = "业务线表"
    def __str__(self):
        return self.name
class IDC(models.Model):
    """
    机房信息
    """
    name = models.CharField(max_length=64)
    floor = models.IntegerField(null=True,blank=True)
    address = models.CharField(max_length=128,null=True,blank=True)
    RackNum = models.CharField(max_length=32)
    class Meta:
        verbose_name_plural = "IDC机房表"
    def __str__(self):
        return self.name
class Rack(models.Model):
    """
    机柜信息
    """
    IDC = models.ForeignKey('IDC',verbose_name='IDC机房',related_name='r_i',on_delete=models.CASCADE)
    cabinet_order = models.CharField('机柜内位置',max_length=24,null=True,blank=True)
    cabinet_num = models.CharField('机柜号',max_length=32,null=True,blank=True)
    class Meta:
        verbose_name_plural = "机房表"
    def __str__(self):
        return self.cabinet_num
class Asset(models.Model):
    """
    资产信息表，所有资产公共信息（交换机，服务器，防火墙等）
    """
    device_type_choices = (
        (1, '服务器'),
        (2, '网络设备'),
        (3, '存储设备'),
        (4, '虚拟机'),
        (5, '云主机'),
    )
    device_status_choices = (
        (1, '待投产'),
        (2, '在线'),
        (3, '离线'),
        (4, '下架'),
    )
    TypeId = models.IntegerField(choices=device_type_choices, default=1)
    # AssetNum = models.CharField('资产编号', max_length=48, default=1)
    device_status = models.IntegerField(choices=device_status_choices, default=1)
    cabinet_num = models.ForeignKey('Rack', verbose_name='所属机柜编号',related_name='R_A',on_delete=models.CASCADE)
    position = models.CharField('机柜中位置', max_length=6, null=True, blank=True)
    form = models.CharField('设备高度', max_length=2, null=True, blank=True)
    AssetNumber = models.CharField('资产编号', max_length=48)
    business_unit = models.ForeignKey('BusinessUnit', verbose_name='属于的业务线', null=True, blank=True,on_delete=models.CASCADE)
    tag = models.ManyToManyField('Tag', null=True, blank=True)
    latest_date = models.DateField(auto_now=True,null=True)
    create_at = models.DateTimeField(auto_now_add=True)
    administrator = models.CharField('管理员',max_length=8, null=True, blank=True)
    comment = models.CharField('设备描述',max_length=24,null=True, blank=True)
    class Meta:
        verbose_name_plural = "资产表"
    def __str__(self):
        return self.get_TypeId_display()
        # return "%s-%s-%s" % (self.idc.name, self.cabinet_num, self.cabinet_order)
class Server(models.Model):
    """
    服务器信息
    """
    asset = models.OneToOneField('Asset',on_delete=models.CASCADE)
    hostname = models.CharField(max_length=128, unique=True)
    sn = models.CharField('SN号', max_length=64, db_index=True)
    manufacturer = models.CharField(verbose_name='制造商', max_length=64, null=True, blank=True)
    model = models.CharField('型号', max_length=64, null=True, blank=True)
    manage_ip = models.GenericIPAddressField('管理IP', null=True, blank=True)
    IpAdress = models.CharField('IP地址', max_length=128, null=True, blank=True)
    DiskInfo = models.CharField('磁盘信息',max_length=512, null=True, blank=True)
    os_platform = models.CharField('系统', max_length=16, null=True, blank=True)
    os_version = models.CharField('系统版本', max_length=16, null=True, blank=True)
    cpu_count = models.IntegerField('CPU个数', null=True, blank=True)
    cpu_physical_count = models.IntegerField('CPU物理个数', null=True, blank=True)
    cpu_model = models.CharField('CPU型号', max_length=128, null=True, blank=True)
    MemSize = models.IntegerField('内存大小', null=True, blank=True)
    MemNumber = models.IntegerField('物理内存个数', null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add=True, blank=True)
    purchasing_time = models.DateField(null=True,blank=True,verbose_name='采购时间')
    # uptime = models.CharField('运行时长', max_length=32, null=True, blank=True)
    class Meta:
        verbose_name_plural = "服务器表"
    def __str__(self):
        return self.hostname
class NetworkDevice(models.Model):
    asset = models.OneToOneField('Asset',on_delete=models.CASCADE)
    management_ip = models.CharField('管理IP', max_length=64, blank=True, null=True)
    vlan_ip = models.CharField('VlanIP', max_length=64, blank=True, null=True)
    intranet_ip = models.CharField('内网IP', max_length=128, blank=True, null=True)
    sn = models.CharField('SN号', max_length=64, blank=True, null=True, unique=True)
    manufacture = models.CharField(verbose_name=u'制造商', max_length=128, null=True, blank=True)
    model = models.CharField('型号', max_length=128, null=True, blank=True)
    port_num = models.SmallIntegerField('端口个数', null=True, blank=True)
    device_detail = models.CharField('设置详细配置', max_length=255, null=True, blank=True)
    class Meta:
        verbose_name_plural = "网络设备"
class TAG(models.Model):
    """
     资产标签
     """
    name = models.CharField('标签', max_length=32, unique=True)
    class Meta:
        verbose_name_plural = "标签表"
    def __str__(self):
        return self.name
class ErrorLog(models.Model):
    """
    错误日志,如：agent采集数据错误 或 运行错误
    """
    asset_obj = models.ForeignKey('Asset', null=True, blank=True,on_delete=models.CASCADE)
    title = models.CharField(max_length=16)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural = "错误日志表"
    def __str__(self):
        return self.title

cmdb/views/asset.py
#/usr/bin/env python
#-*- coding: utf-8 -*-

from django.views import View
from django.shortcuts import render,HttpResponse
from django.http import JsonResponse
from cmdb.models import *
from cmdb.forms import *
from cmdb.views.permission import check_permission
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
class Location(View):
    def get(self,request):
        data=request.GET
        if request.path == '/dcroom/':
            nid = data.get('nid')
            IDCinfo = IDC.objects.filter(id=nid).all()
            return render(request,'dcroom.html',locals())
        elif request.path == '/location/':
            datacenter = IDC.objects.all()
            return render(request, 'datacenter.html', {'datacenter':datacenter})
    @method_decorator(check_permission)
    def post(self,request):
        data = request.POST
        print(data)
        if request.path == '/dcroom/':
            Rack.objects.create(cabinet_num=data.get('RackNum'),cabinet_order=data.get('cabinet_order'),IDC_id=data.get('idc_id'))
            return HttpResponse('ok')
        else:
            if data.get('status') == 'update':
                XY = data.getlist('XY[]')[1]+'*'+data.getlist('XY[]')[0]
                obj_idc = IDC.objects.filter(id=data.get('id'))
                obj_idc.update(name=data.get('name'),floor=data.get('floor'),address=data.get('address'),RackNum=XY)
            else:
                cabinet_order = data.get('X')+'*'+data.get('Y')
                IDC.objects.create(name=data.get('name'),floor=data.get('floor'),address=data.get('address'),RackNum=cabinet_order)
            return HttpResponse('ok')
class AssetInfo(View):
    def __init__(self):
        self.dic = []
    @method_decorator(check_permission)
    # @login_required()
    def get(self,request):
        server = Server.objects.all()
        networkdeviceinfo = NetworkDevice.objects.all()
        serverinfo = []
        serverinfo.extend(server)
        serverinfo.extend(networkdeviceinfo)
        AssetSearchFields = AssetSearchField()#搜索框参数
        paginator = Paginator(serverinfo,20)
        page = request.GET.get('page')
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            contacts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            contacts = paginator.page(paginator.num_pages)
        return render(request, 'asset.html', {'ServerInfo':contacts,'AssetSearchFields':AssetSearchFields})
    @method_decorator(check_permission)
    def post(self, request):
        if request.POST.get('RemoveAsset')=='True':
            remove_server = Server.objects.filter(id=request.POST.get('nid')).all()
            remove_other = NetworkDevice.objects.filter(id=request.POST.get('nid')).all()
            if remove_server:
                for i in remove_server:
                    Asset.objects.filter(id=i.asset_id).delete()
                    Server.objects.filter(id=i.id).delete()
            elif remove_other:
                for i in remove_other:
                    Asset.objects.filter(id=i.asset_id).delete()
                    NetworkDevice.objects.filter(id=i.id).delete()
        return HttpResponse('ok')
class AssetDetail(View):
    def get(self,request):
        nid = request.GET.get('nid')
        data = Server.objects.filter(id=nid).all()
        nic = []
        address=[]
        try:
            for i in data:
                if i.IpAdress:
                   for k,v in (eval(i.IpAdress)).items():
                       nic.append(k)
                       address.append(v)
        except:
            pass
        return render(request,'detail.html',locals())
class CRM(View):
    def __init__(self):
        self.v1 = Django_test.objects.all()
        self.classess = Classes.objects.all()
        self.Teacheress = Teacheres.objects.all()
        self.Studentss = Students.objects.all()
    def get(self, request):
        if request.path == '/muotai/':
            return render(request,'muotai.html')
        elif request.path == '/set_teacher/':
            nid = request.GET.get('nid')
            teacher_list = Teacheres.objects.all()
            return render(request, 'set_teacher.html', {'teacher_list':teacher_list, 'nid':nid})
            # return render(request,'set_teacher.html',{'cls_teacher':cls_teacher})
        else:
            v1 =Classes.objects.all()
            return render(request,'students.html',{'v11':self.v1,'v1': self.classess, 'v2': self.Teacheress, 'v3': self.Studentss})
    def post(self,request):
        data = request.POST
        for i in data:
            if data.get('status') == 'delete':
                if not data.get('select'):
                    pass
                else:
                    for i in data.getlist('select',''):#getlist方法可以在同时删除多个id的时候循环获取列表里的每一项
                        Django_test.objects.filter(id=i).delete()
                        return redirect('/students/')
            elif data.get('status') == 'setup':
                nid = data.get('nid')
                teacher = data.getlist('teacher')
                obj = Classes.objects.filter(id=nid).first()

                obj.teacher.set(teacher)
                return redirect('/students/')
            elif data.get('status') == 'update':
                pass
            elif data.get('status') == 'submit':
                if request.path == '/students/':
                    if(data.get('name') == '' or data.get('age') == ''):
                        pass
                    else:
                        Students.objects.create(name=data.get('name'), age=data.get('age'),
                                                class_name_id=data.get('classes'), gender=data.get('gender'))
                    return redirect('/crm/')
                elif request.path == '/classes/':
                    if (data.get('captioin')=='' or data.get('code')==''):
                        pass
                    else:
                        Classes.objects.create(classname=data.get('caption'))
                        cls_obj = Classes.objects.filter(classname=data.get('caption')).first()
                        for i in data.get('teachers_id'):
                            cls_obj.teacher.add(i)
                    return redirect('/crm/')
                elif request.path == '/teachers/':
                    Teacheres.objects.create(name=data.get('TeacherName'))
                    return redirect('/crm/')
            else:
                return redirect('/students/')

templates/asset.html
{% extends 'layout.html' %}
{% block css %}

{% endblock %}
{% block conent %}
    <div id="SearchBox" style="padding-bottom: 20px">
    <form action="/search/" method="post">
    <div class="input-group" style="width: 70%;margin:0 auto">
        <span  class="input-group-btn">
          <a id="add" class="btn btn-default no-radius" ><i class="fa fa-plus-square" ></i></i></a>
            <a id="del" style="display: none" class="btn btn-default no-radius" ><i class="fa fa-minus-square" ></i></a>
        </span>
        <select id="SearchField" style="width: 110px;display: none" class="form-control" name="Searchindex">Searchindex</select>
        {{ AssetSearchFields.TypeId }}{{ AssetSearchFields.device_status }}
        <input style="width: 400px;" type="text" name="q" class="form-control" placeholder="Search...">
        <span style="display: inline-block" class="input-group-btn">
          <button type="submit" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
          </button>
        </span>
    </div>
    </div>
    </form>
        {% if ServerInfo or NetworkDeviceInfo %}
        <table class="table table-condensed table-bordered table-hover">
            <tr>
                <th>选择</th>
                <th>资产类型</th>
                <th>主机名</th>
                <th>设备序列号</th>
                <th>IDC</th>
                <th>机柜号</th>
                <th>位置</th>
                <th>资产状态</th>
                <th>选项</th>
            </tr>
                {% for i in ServerInfo.object_list %}
                <tr>
                    <td><input id="nid" type="checkbox" name="DeviceID" value="{{ i.id }}" ></td>
                    <td>{{ i.asset.get_TypeId_display}}</td>
                    <td class="edit" edit="true" type="input">{{ i.hostname }}</td>
                    <td>{{ i.sn }}</td>
                    <td>{{ i.asset.cabinet_num.IDC.name }}</td>
                    <td>{{ i.asset.cabinet_num }}</td>
                    <td class="edit" edit="true" type="input">{{ i.asset.position }}</td>
                    <td>{{ i.asset.get_device_status_display }}</td>
                    <td><a href="/detail/?nid={{ i.id }}">详细信息</a> <a control="删除" href="" data-toggle="modal" data-target=".sub-confirm" style="color: #0d8ddb" class="glyphicon glyphicon-trash removee"></a></td>
                </tr>
                {% endfor %}
        {% else %}
            <div>NO DATA</div>
        {% endif %}
        </table>
    </div>
    <ul class="pagination">
        {# 如果当前页还有上一页 #}
        {% if ServerInfo.has_previous %}
            <li>
                {# 点击a标签，跳转到上一页链接 ?index  为地址后面拼接的参数 #}
                {% if wd %}{% if action %}<a href="?wd={{ wd }}&{{ action }}&page={{ServerInfo.previous_page_number}}">上一页</a>{% else %}<a href="?wd={{ wd }}&page={{ServerInfo.previous_page_number}}">上一页</a>{% endif %}{% else %}<a href="?page={{ServerInfo.previous_page_number}}">上一页</a>{% endif %}
            </li>
        {% else %}
            {# 如果没有上一页， 则上一页按钮不可点击 #}
            <li class="disabled">
                <a href="#">上一页</a>
            </li>
        {% endif %}

        {% for pg in ServerInfo.paginator.page_range %}
            {% if ServerInfo.number == pg %}
                {% if wd %}
                    {% if action %}
                        <li class="active"><a href="?wd={{ wd }}&{{ action }}&page={{ pg }}">{{ pg }}</a></li>
                    {% else %}
                        <li class="active"><a href="?wd={{ wd }}&page={{ pg }}">{{ pg }}</a></li>
                    {% endif %}
                {% else %}
                    <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
                {% endif %}
            {% else %}
                {% if wd %}
                    {% if action %}
                        <li><a href="?wd={{ wd }}&{{ action }}&page={{ pg }}">{{ pg }}</a> </li>
                    {% else %}
                        <li><a href="?wd={{ wd }}&page={{ pg }}">{{ pg }}</a> </li>
                    {% endif %}
                {% else %}
                    {% if action %}
                        <li><a href="?{{ action }}&page={{ pg }}">{{ pg }}</a> </li>
                    {% else %}
                        <li><a href="?page={{ pg }}">{{ pg }}</a> </li>
                    {% endif %}
                {% endif %}
            {% endif %}
        {% endfor %}
        {% if ServerInfo.has_next %}
            <li>
                {% if wd %}
                    {% if action %}
                        <a href="?wd={{ wd }}&{{ action }}&page={{ServerInfo.next_page_number}}">下一页</a>
                    {% else %}
                        <a href="?wd={{ wd }}&page={{ServerInfo.next_page_number}}">下一页</a>
                    {% endif %}
                {% else %}
                    {% if action %}
                        <a href="?{{ action }}&page={{ServerInfo.next_page_number}}">下一页</a>
                    {% else %}
                        <a href="?page={{ServerInfo.next_page_number}}">下一页</a>
                    {% endif %}
                {% endif %}
            </li>
        {% else %}
        <li class="disabled">
            <a href="#">下一页</a>
        </li>
        {% endif %}
    </ul>
{% endblock %}
{% block model %}
    <div class="modal fade sub-confirm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
 <div class="modal-dialog modal-sm" role="document">
  <div class="modal-content">
   <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
   </div>
   <div class="modal-body">
    <form>
    <div class="form-group">
      <label for="message-text" id="confirm" class="control-label"></label>
     </div>
    </form>
   </div>
   <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">返回</button>
    <button type="button" id="DelAsset" class="btn btn-success" data-dismiss="modal">确认</button>
   </div>
  </div>
 </div>
</div>
{% endblock %}
{% block js %}
    <script src="/static/jquery.min(1).js"></script>
    <script src="/static/message.js"></script>
    <script src="/static/45e31a2159c1bfeb.js"></script>
{% endblock %}

templates/cabinet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/detail.html
{% extends 'layout.html' %}
{% block js %}
    <link rel="stylesheet" href="https://apps.bdimg.com/libs/bootstrap/3.2.0/css/bootstrap.min.css">
{% endblock %}
{% block conent %}
 {% for i in data %}
     <div class="main-container">
                <div class="card-head">
                    <p id="head">业务</p>
                </div>
                <div class="card-body">
                    <div class="card-row">
                        <div class="Graph">
                            <div class="term"><p>所属IDC</p></div>
                            <div class="val"><p>{{ i.asset.cabinet_num.IDC.name }}</p></div>
                        </div>
                        <div class="Graph">
                            <div class="term"><p>所属机柜</p></div>
                            <div class="val"><p>{{ i.asset.cabinet_num.cabinet_num }}</p></div>
                        </div>
                        <div class="Graph">
                            <div class="term"><p>设备类型</p></div>
                            <div class="val"><p>{{ i.asset.get_TypeId_display }}</p></div>
                        </div>
                        <div class="Graph">
                            <div class="term"><p>状态</p></div>
                            <div class="val"><p>{{ i.asset.get_device_status_display }}</p></div>
                        </div>
                        <div class="Graph">
                            <div class="term"><p>环境</p></div>
                            <div class="val"><p></p></div>
                        </div>
{#                        问题就在下面这个div把head挤到边上了。#}
                        <div class="Graph">
                            <div class="term"><p>负责人</p></div>
                            <div class="val"><p>{{ i.asset.administrator }}</p></div>
                        </div>
                    </div>
                </div>
                 <div class="card-head">
                    <p id="head">硬件</p>
                </div>
                <div class="card-body">
                    <div class="card-row-max">
                        <div class="Graph">
                            <div class="term"><p>序列号</p></div>
                            <div class="val"><p>{{ i.sn }}</p></div>
                        </div>
                        <div class="Graph">
                            <div class="term"><p>CPU型号</p></div>
                            <div class="val"><p>{{ i.cpu_model }}</p></div>
                        </div>
                        <div class="Graph">
                            <div class="term"><p>CPU物理核数</p></div>
                            <div class="val"><p>{{ i.cpu_physical_count }}</p></div>
                        </div>
                        <div class="Graph">
                            <div class="term"><p>CPU逻辑核数</p></div>
                            <div class="val"><p>{{ i.cpu_count }}</p></div>
                        </div>
                        <div class="Graph">
                            <div class="term"><p>内存大小</p></div>
                            <div class="val"><p>{{ i.MemSize }}</p></div>
                        </div>
                        <div class="Graph">
                            <div class="term"><p>内存数量</p></div>
                            <div class="val"><p>{{ i.MemNumber }}</p></div>
                        </div>
                        <div class="Graph">
                            <div class="term"><p>磁盘空间</p></div>
                            <div class="val"><p>{{ i.DiskInfo }}</p></div>
                        </div>
                        <div class="Graph">
                            <div class="term"><p>RAID</p></div>
                            <div class="val"><p></p></div>
                        </div>
                    </div>
                </div>
                 <div class="card-head">
                    <p id="head">系统</p>
                </div>
                <div class="card-body">
                    <div class="card-row">
                        <div class="Graph">
                            <div class="term"><p>主机名</p></div>
                            <div class="val"><p>{{ i.hostname }}</p></div>
                        </div>
                        <div class="Graph">
                            <div class="term"><p>IP地址</p></div>
                            {% for i in address %}
                                <div class="val"><p>{{ i }}</p></div>
                            {% endfor %}
                        </div>
                        <div class="Graph">
                            <div class="term"><p>操作系统版本</p></div>
                            <div class="val"><p>{{ i.os_version }}</p></div>
                        </div>
                        <div class="Graph">
                            <div class="term"><p>内核版本</p></div>
                            <div class="val"><p></p></div>
                        </div>
                    </div>
                </div>
                  <div class="card-head">
                    <p id="head">其他</p>
                </div>
                <div class="card-body">
                    <div class="card-row">
                        <div class="Graph">
                            <div class="term"><p>品牌型号</p></div>
                            <div class="val"><p>{{ i.manufacturer }}{{ i.model }}</p></div>
                        </div>
                        <div class="Graph">
                            <div class="term"><p>采购日期</p></div>
                            <div class="val"><p></p></div>
                        </div>
                        <div class="Graph">
                            <div class="term"><p>保修结束日期</p></div>
                            <div class="val"><p></p></div>
                        </div>
                    </div>
                </div>
     </div>
{% endfor %}
{% endblock %}

templates/header_menu.html
    <div class="logo left" style="text-align: center;background-color: #1c5a9c;">
        <a href="#" style="color: #ffffff;font-size:30px;font-weight: bold;text-decoration: none">
            AutoCMDB
        </a>
    </div>

    <div class="left-menu left">
        <a class="menu-item" href="/index.html">平台首页</a>
        <a class="menu-item" href="/cmdb.html">资产首页</a>
    </div>

    <div class="right-menu right clearfix">

        <div class="user-info right">
            <a href="#" class="avatar">
{#                <img class="img-circle" src="/static/imgs/avatar/default.png">#}
            </a>

            <div class="more-info">
                <a href="#" class="more-item">个人信息</a>
                <a href="/logout.html" class="more-item">注销</a>
            </div>
        </div>

        <a class="user-menu right">
            消息
            <i class="fa fa-commenting-o" aria-hidden="true"></i>
            <span class="badge bg-success">2</span>
        </a>

        <a class="user-menu right">
            通知
            <i class="fa fa-envelope-o" aria-hidden="true"></i>
            <span class="badge bg-success">2</span>
        </a>

        <a class="user-menu right">
            任务
            <i class="fa fa-bell-o" aria-hidden="true"></i>
            <span class="badge bg-danger">4</span>
        </a>
    </div>

templates/login.html
{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/login.css"/>
{% endblock %}


{% block conent %}
<body align="center" class="login">
    <div id="content-main">
        <div class="head"> 登录CMDB系统</div>
        <form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
            <div class="form-row">
                {{ userinfo.username.errors }}
                {{ userinfo.username.label_tag }} {{ userinfo.username }}
            </div>
            <div class="form-row">
                {{ userinfo.password.errors }}
                {{ userinfo.password.label_tag }} {{ userinfo.password }}
                <input type="hidden" name="next" value="{{ next }}" />
            </div>
            <div class="submit-row">
                <label>&nbsp;</label><input type="submit" value="Log in" />
            </div>
        </form>
        </div>
    </div>
</body>
{% endblock %}